version: '3.9'
services:
  redis:
    restart: unless-stopped
    container_name: <django_package_name>-redis
    image: redis:4.0.6
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  rabbitmq:
    restart: unless-stopped
    container_name: <django_package_name>-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: '<django_package_name>'
  webserver:
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - RABBIT_HOST=rabbitmq
      - REDIS_CONN_STR=redis://redis:6379/1
    depends_on:
      - redis
      - rabbitmq
    build:
      context: .
      dockerfile: docker/webserver.Dockerfile
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/app/logs
    ports:
      - "80:80"